[package]
name = "r4d"
version = "1.2.0"
edition = "2018"
license = "MIT OR Apache-2.0"
keywords = ["macro", "cli", "text-processing"]
categories = ["command-line-utilities", "text-processing"]
description = "Text oriented macro processor"
homepage = "https://github.com/simhyeon/r4d"
repository = "https://github.com/simhyeon/r4d"
readme = "README.md"

[[bin]]
name = "rad"
path = "src/bin.rs"

[lib]
name = "rad"
path = "src/lib.rs"

[features]
binary = [ "csv", "evalexpr", "lipsum", "chrono", "clap", "debug"]
full = [ "csv", "evalexpr", "lipsum", "chrono" ]
debug = [ "crossterm", "similar" ]
color = [ "colored" ]

[dependencies]
bincode = "1.3.3"
chrono = {version = "0.4.19", optional = true}
clap = { version = "3.0.0-beta.2", optional = true }
colored = {version = "2.0.0", optional = true}
csv = {version = "1.1.6", optional = true}
evalexpr = {version = "6.4.0", optional = true}
lazy_static = "1.4.0"
lipsum = {version = "0.8.0", optional = true}
regex = "1.5.4"
serde = { version = "1.0.126", features = ["derive"]}
thiserror = "1.0.25"
crossterm = {version = "0.20.0", optional = true}
similar = { version = "2.0.0", optional = true}
