[package]
name = "r4d"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.25"
clap = "3.0.0-beta.2"
regex = "1.5.4"
evalexpr = "6.4.0"
lipsum = "0.8.0"
