[package]
name = "rad"
version = "0.1.0"
edition = "2018"

[dependencies]
thiserror = "1.0.25"
clap = "3.0.0-beta.2"
regex = "1.5.4"
evalexpr = "6.4.0"
lipsum = "0.8.0"
csv = "1.1.6"
chrono = "0.4.19"
