[package]
name = "r4d"
version = "2.1.4"
edition = "2018"
license = "MIT OR Apache-2.0"
keywords = ["macro", "cli", "text-processing"]
categories = ["command-line-utilities", "text-processing"]
description = "Text oriented macro processor"
homepage = "https://github.com/simhyeon/r4d"
repository = "https://github.com/simhyeon/r4d"
readme = "README.md"

[[bin]]
name = "rad"
path = "src/bin.rs"

[lib]
name = "rad"
path = "src/lib.rs"
crate-type = ["cdylib","rlib"]

[features]
default = ["for_macro"]
basic = ["clap"]
binary = ["clap","debug", "full"]
full = [ "evalexpr", "chrono", "textwrap", "cindex"]

debug = [ "crossterm", "similar" ]
color = [ "colored" ]
hook = []
storage = []
signature = ["serde_json"]
wasm = ["wasm-bindgen", "console_error_panic_hook"]
template = ["rad_ext_template"]

# Backword compatibility features
for_macro = []

[dependencies]
bincode = "1.3.3"
regex = "1.5.4"
lazy_static = "1.4.0"
dcsv = { git="https://github.com/simhyeon/dcsv", branch = "dev",version = "0.1.4"}
chrono = {version = "0.4.19", optional = true}
clap = { version = "3.0.0", default-features = false, features = ["std"], optional=true}
colored = {version = "2.0.0", optional = true}
crossterm = {version = "0.20.0", optional = true}
evalexpr = {version = "6.4.0", optional = true}
serde = { version = "1.0.126", features = ["derive"]}
serde_json = { version = "1.0", optional = true}
similar = { version = "2.0.0", optional = true}
textwrap = { version = "0.14.2", optional = true}
cindex = { git="https://github.com/simhyeon/cindex", version = "0.4.0", optional = true, default-features = false}
rad_ext_template = { version="0.1.0", optional = true}

# Wasm related dependencies
wasm-bindgen = { version = "0.2.74", optional = true}
console_error_panic_hook = { version = "0.1.7", optional = true}
wee_alloc = { version = "0.4.5", optional = true }
