[package]
name = "rad"
version = "0.1.0"
edition = "2018"
license = "MIT OR Apache-2.0"
keywords = ["macro", "text processing"]
categories = ["command-line-utilities"]
description = "Text oriented macro processor"
homepage = "https://github.com/simhyeon/r4d"
repository = "https://github.com/simhyeon/r4d"
readme = "README.md"

[dependencies]
thiserror = "1.0.25"
clap = "3.0.0-beta.2"
regex = "1.5.4"
evalexpr = "6.4.0"
lipsum = "0.8.0"
csv = "1.1.6"
chrono = "0.4.19"
